services:
  mysql:
    image: mysql:8.0.27
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d

  connect:
    build:
      context: .
      dockerfile: connect/Dockerfile
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=debezium_configs
      - OFFSET_STORAGE_TOPIC=debezium_offsets
      - STATUS_STORAGE_TOPIC=debezium_statuses
    ports:
      - 8083:8083
    volumes:
      - ./secrets:/secrets
  debezium-ui:
    image: debezium/debezium-ui:latest
    ports:
      - 8090:8080
    environment:
      KAFKA_CONNECT_URIS: http://connect:8083

  zookeeper:
    image: zookeeper:3.9.0
    ports:
      - 2181:2181
  kafka:
    image: docker.io/bitnami/kafka:3.4
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - 8091:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

  # flink-jobmanager:
  #   image: flink:latest
  #   ports:
  #     - "8092:8081"
  #   environment:
  #     FLINK_PROPERTIES: "jobmanager.rpc.address: flink-jobmanager"
  #   command: jobmanager
  #   tty: true
  # flink-taskmanager:
  #   image: flink:latest
  #   environment:
  #     FLINK_PROPERTIES: "jobmanager.rpc.address: flink-jobmanager"
  #   command: taskmanager
  #   tty: true

networks:
  default:
    name: devcontainer-network
    external: true
